#!/bin/sh
# =============================================================================
# docker-entrypoint.sh — Injects runtime config, then starts nginx
# =============================================================================
# WHAT THIS DOES:
# 1. Reads the API_URL environment variable (set by Railway)
# 2. Writes it into a config.js file that the browser loads
# 3. Starts nginx
#
# WHY THIS WORKS:
# The browser loads config.js BEFORE the React bundle runs.
# config.js sets window.SPARK_API_URL = "https://real-url.railway.app"
# React reads this value instead of the baked-in placeholder.
# =============================================================================

# Default to localhost if API_URL not set (for local testing)
API_URL="${API_URL:-http://localhost:8000}"

echo "Starting SPARK-Bayern frontend"
echo "API URL: $API_URL"

# Write the runtime config file into the web root
# The browser will fetch this before loading React
cat > /usr/share/nginx/html/config.js << EOF
// Runtime configuration — generated at container startup
// Do not edit this file manually — set the API_URL environment variable instead
window.SPARK_CONFIG = {
  apiUrl: "${API_URL}"
};
EOF

echo "Config written. Starting nginx..."
exec nginx -g "daemon off;"
